Imports Business
Imports System.Data
Imports System.Data.Sql

Partial Class Profile_add
    Inherits System.Web.UI.Page

    Private Sub Page_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        'Put user code to initialize the page here
        Call Me.Load_JavaScript()

        If Not Page.IsPostBack Then
            Dim Errmsg As String
            Dim strUsername As String
            Errmsg = Trim(Request.QueryString("msg"))
            strUsername = Trim(Request.QueryString("username"))
            Select Case Errmsg

                Case "Invalid"
                    'Call Me.AriseJavaScript("'The Acct ID You Entered Is Invalid.'")
                    Call Me.AriseJavaScript("'Online Profile Creation is prohibited for this account. Please contact your administrator for further details.'")
                    Me.txtUsername.Text = strUsername
                Case "InvalidCard"
                    Call Me.AriseJavaScript("'The Card # You Entered Is Invalid.'")
                    Me.txtUsername.Text = strUsername
                Case "nosharefld"
                    Call Me.AriseJavaScript("'Shared Folder NOT found!'")
                    Me.txtUsername.Text = strUsername
                Case "verservicebusy"
                    Call Me.AriseJavaScript("'Verification Service Busy!'")
                    Me.txtUsername.Text = strUsername
                Case "collision"
                    Call Me.AriseJavaScript("'A Collision happened between ICverify users!'")
                    Me.txtUsername.Text = strUsername
                Case "errgen"
                    Call Me.AriseJavaScript("'A error was generated by'")
                    Me.txtUsername.Text = strUsername
                Case "noinitvar"
                    Call Me.AriseJavaScript("'Error init sys. param.'")
                    Me.txtUsername.Text = strUsername
                Case "dupusr"
                    Call Me.AriseJavaScript("'Duplicate User.'")
                    Me.txtUsername.Text = strUsername
                Case "4006"
                    Call Me.AriseJavaScript("'The user name entered is already used. Please enter another user name.'")
                    Me.txtUsername.Text = strUsername
                Case "ready"
                    Call Me.AriseJavaScript("'A matching profile already exists. Please contact APEX for assistance.'")
                    Me.txtUsername.Text = strUsername
                Case "no"
                    Call Me.AriseJavaScript("'No User Found. Please Try again'")
                    Me.txtUsername.Text = strUsername
                Case "cnerror"
                    Call Me.AriseJavaScript("'Connect SQL Server Error!'")
                    Me.txtUsername.Text = strUsername
                Case Else
                    '--do nothing
            End Select
            Errmsg = Nothing
            strUsername = Nothing

            Call Load_Default()

            'Call getAccountInfo()

        End If
    End Sub

#Region "Private Sub Pages"

    Protected Sub ImageSubmit_Click(ByVal sender As Object, ByVal e As System.Web.UI.ImageClickEventArgs) Handles ImageSubmit.Click
        Using objuser As New Users
            Dim userdata As New UserData
            With userdata
                .fname = Me.txtFname.Text.Trim
                .lname = Me.txtLname.Text.Trim
                .Company = Me.txtCompany.Text.Trim
                .username = Me.txtUsername.Text.Trim
                .acct_id = Me.txtAcctId.Text.Trim
                .password = Me.txtPassword.Text.Trim
                .CCType = Me.ddlCardType.SelectedValue
                .CCNo = Me.txtCardNo.Text.Trim
                .CCYear = Me.ddlYear.SelectedValue.PadLeft(2, "0")
                .CCMonth = Me.ddlMonth.SelectedValue.PadLeft(2, "0")
                .contact = Me.txtContact.Text.Trim
                .office_phone = Me.txtPhoneArea.Text.Trim
                .office_phone_ext = Me.txtPhonetail.Text.Trim
                .cell_phone = Me.txtCellPhoneArea.Text.Trim
                .fax = Me.txtFaxArea.Text.Trim
                .home_phone = Me.txtHomePage.Text.Trim
                .pager_no = Me.txtPager.Text.Trim
                .office_phone_area = Me.txtPhone2.Text.Trim
                .email = Me.txtEmail.Text.Trim
                .st_name = Me.txtStName.Text.Trim
                .st_no = Me.txtStNo.Text.Trim
                .city = Me.txtCity.Text.Trim
                .state = Me.txtState.Text.Trim
                .zip_code = Me.txtZip.Text.Trim
                .sub_zip = Me.txtSubzip.Text.Trim
            End With

            'MySession.OperatorOrder.card_no = userdata.CCNo
            'MySession.OperatorOrder.card_exp_date = userdata.CCMonth & userdata.CCYear
            'MySession.OperatorOrder.card_type = userdata.CCType

            If userdata.acct_id.Trim.Length = 0 Then
                '## 1/11/2008   If user does not enter the acct id. Default to quick user acct id ("CC")    (Joey, modified by yang)
                userdata.acct_id = System.Web.Configuration.WebConfigurationManager.AppSettings("QuickOrderDefaultAcctID")
            End If

            Dim strVipNo As String = ""
            Dim out As Integer = objuser.InsertVip(userdata, strVipNo)

            'MySession.OperatorOrder.card_no = ""
            'MySession.OperatorOrder.card_exp_date = ""
            'MySession.OperatorOrder.card_type = ""

            If out = 1 Then
                MySession.UserID = strVipNo
                Me.SendEmail()
            ElseIf out = -1 Then
                Me.AriseJavaScript("'A matching profile already exists. Please contact APEX for assistance.'")
            ElseIf out = -2 Then
                Me.AriseJavaScript("'Online Profile Creation is prohibited for this account. Please contact your administrator for further details.'")
            ElseIf out = -3 Then
                Me.AriseJavaScript("'The user name entered is already used. Please enter another user name.'")
            End If

        End Using
    End Sub

    Protected Sub SubmitHide_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles SubmitHide.Click
        Me.ImageSubmit_Click(Nothing, Nothing)
    End Sub

    'add by nair 05/30/2006
    Protected Sub ImageReset_ServerClick(ByVal sender As Object, ByVal e As System.Web.UI.ImageClickEventArgs) Handles ImageReset.ServerClick
        SetTextBoxValue(Me, "")
        Call Load_Default()
    End Sub

#End Region

#Region " Private Sub"

    '## added by joey   1/10/2008
    Private Sub SendEmail()
        '---------Send Email----------------
        Dim strBody As String
        Dim strTitle As String
        strTitle = "APEX: New User Request Form"

        strBody = ""

        strBody = strBody & "First Name  :  " & Me.txtFname.Text.Trim() & "<br>"
        strBody = strBody & "Last Name   :  " & Me.txtLname.Text.Trim() & "<br>"
        strBody = strBody & "Company     :  " & Me.txtCompany.Text.Trim() & "<br>"

        If Me.txtAcctId.Text.Trim.Length > 0 Then
            strBody = strBody & "Acct Name   :  " & Me.txtAcctId.Text.Trim() & "<br>"
        Else
            strBody = strBody & "Acct Name   :  " & System.Web.Configuration.WebConfigurationManager.AppSettings("QuickOrderDefaultAcctID") & "<br>"
        End If

        strBody = strBody & "User Name   :  " & Me.txtUsername.Text.Trim() & "<br>"
        strBody = strBody & "Password    :  " & Me.txtPassword.Text.Trim() & "<br>"

        'strBody = strBody & "Cost Center#:  " & Me.txtConfir.Text.Trim() & "<br>"
        'strBody = strBody & "Emp #       :  " & Me.txtEmp.Text.Trim() & "<br>"

        '## 1/23/2008   Disable Credit Card in new user request email
        'strBody = strBody & "Credit Card#:  " & Me.txtCardNo.Text.Trim() & "<br>"
        'strBody = strBody & "CC# Exp Date:  " & Me.ddlMonth.SelectedValue.Trim() & "/" & Me.ddlYear.SelectedValue.Trim() & "<br>"

        strBody = strBody & "Contact     :  " & Me.txtContact.Text.Trim() & "<br>"
        strBody = strBody & "Phone       :  " & Me.txtPhoneArea.Text.Trim() & "<br>"
        strBody = strBody & "Phone Ext   :  " & Me.txtPhonetail.Text.Trim() & "<br>"
        strBody = strBody & "Cell Phone  :  " & Me.txtCellPhoneArea.Text.Trim() & "<br>"
        strBody = strBody & "Fax #       :  " & Me.txtFaxArea.Text.Trim() & "<br>"
        strBody = strBody & "Home Phone  :  " & Me.txtHomePage.Text.Trim() & "<br>"
        strBody = strBody & "Page #      :  " & Me.txtPager.Text.Trim() & "<br>"
        strBody = strBody & "Telephone # 2:  " & Me.txtPhone2.Text.Trim() & "<br>"
        strBody = strBody & "Email       :  " & Me.txtEmail.Text.Trim() & "<br>"

        strBody = strBody & "Street No   :  " & Me.txtStNo.Text.Trim() & "<br>"
        strBody = strBody & "Street Name :  " & Me.txtStName.Text.Trim() & "<br>"
        'strBody = strBody & "Street Add2 :  " & Me.txtAuxAddress.Text.Trim() & "<br>"
        strBody = strBody & "City        :  " & Me.txtCity.Text.Trim() & "<br>"
        strBody = strBody & "State       :  " & Me.txtState.Text.Trim() & "<br>"
        strBody = strBody & "Zip Code    :  " & Me.txtZip.Text.Trim() & "<br>"
        strBody = strBody & "SubZip Code :  " & Me.txtSubzip.Text.Trim() & "<br>"
        'strBody = strBody & "Country     :  " & Me.txtCountry.Text.Trim() & "<br>"

        Dim blnResult As String

        Dim MailTo As String = System.Web.Configuration.WebConfigurationManager.AppSettings("NewUserMailTo")
        Dim MailCc As String = System.Web.Configuration.WebConfigurationManager.AppSettings("NewUserMailCc")

        Dim MailBcc As String = System.Web.Configuration.WebConfigurationManager.AppSettings("MailBcc")
        blnResult = Business.Mail.SendEmail(Me.txtEmail.Text.Trim, MailTo, MailCc, MailBcc, strTitle, strBody, True)

        If blnResult = "Success" Then
            Me.lblErr.Text = "Your request form has been sent and is being processed. "
            Me.trlink.Visible = True

        Else
            Me.lblErr.Text = String.Format("There is a problem with the information you added.<br />Please contact <a href='mailto:{0}'>{0}</a> for assistance.", MailTo)
        End If
    End Sub

    '-----------------------------------------------------------------------------------
    '--Sub:AriseJavaScript
    '--Description:To show the error message
    '--Input:ErrorMessage
    '--Output:
    '--11/09/04 - Created (eJay)
    '-----------------------------------------------------------------------------------
    Private Sub AriseJavaScript(ByVal ErrorMessage As String)

        Dim strMessage As String
        strMessage = "<script language='javascript'>alert(" & ErrorMessage & ");</script>"
        RegisterStartupScript("PopUpMessage", strMessage)

    End Sub
    '-----------------------------------------------------------
    '--Sub:Load_default
    '--Description:Load default value when Page Load or Reload
    '--Input:
    '--Output:
    '-- 11/17/04 - Created (eJay)
    '-----------------------------------------------------------
    Private Sub Load_Default()

        Me.ddlYear.Items.Clear()
        Me.ddlMonth.Items.Clear()
        Me.ddlCardType.Items.Clear()

        '--1.Card Type
        Dim objCard As New Card
        Me.ddlCardType.DataSource = objCard.getAllCardType
        With Me.ddlCardType
            .DataTextField = "card_type_desc"
            .DataValueField = "card_type_id"
            .DataBind()
            .Items.Insert(0, New ListItem("Credit Card Type", "0"))
        End With
        objCard.Dispose()
        objCard = Nothing

        '--2.YEAR
        Dim i As Int32
        ddlYear.Items.Add("Year")
        For i = 0 To 10
            Dim iYear As Int32
            iYear = Convert.ToInt32(Right(Now().Year.ToString, 2))
            iYear = iYear + i
            If iYear >= 10 Then
                ddlYear.Items.Add(iYear.ToString)
            Else
                ddlYear.Items.Add("0" & iYear.ToString)
            End If
        Next

        '--3.Month
        Me.ddlMonth.Items.Add("Month")
        For i = 1 To 12
            Me.ddlMonth.Items.Add(New ListItem(MonthName(i, True), Convert.ToString(i).PadLeft(2, Char.Parse("0"))))
        Next

        If Session("new_fname") <> "" And Session("new_lname") <> "" Then
            Me.txtFname.Text = Session("new_fname")
            Me.txtLname.Text = Session("new_lname").ToString
            Me.txtCompany.Text = Session("new_company").ToString
            Me.txtAcctId.Text = Session("new_acctid").ToString
            Me.txtUsername.Text = Session("new_username").ToString
            Me.txtPassword.Text = Session("new_password").ToString
            Me.txtCardNo.Text = Session("new_cardno").ToString
            '==Card Type
            With Me.ddlCardType
                If Session("new_cardtype").ToString Is Nothing Or Session("new_cardtype").ToString = "" Then
                    '--do nothing
                    .SelectedIndex = 0
                ElseIf .Items.FindByValue(Session("new_cardtype").ToString) Is Nothing Then
                    '--do nothing
                    .SelectedIndex = 0
                Else
                    '## 1/25/2008   Modified by yang
                    '.Items.FindByValue(Session("new_cardtype").ToString).Selected = True
                    Common.ShowDropDownValue(Me.ddlCardType, Session("new_cardtype").ToString, False)
                End If
            End With
            '==Month
            With Me.ddlMonth
                If Session("new_month").ToString Is Nothing Or Session("new_month").ToString = "" Then
                    '--do nothing
                    .SelectedIndex = 0
                ElseIf .Items.FindByValue(Session("new_month").ToString) Is Nothing Then
                    '--do nothing
                    .SelectedIndex = 0
                Else
                    '## 1/25/2008   Modified by yang
                    '.Items.FindByValue(Session("new_month").ToString).Selected = True
                    Common.ShowDropDownValue(Me.ddlMonth, Session("new_month").ToString, True)
                End If
            End With
            '==Year
            With Me.ddlYear
                If Session("new_year").ToString Is Nothing Or Session("new_year").ToString = "" Then
                    '--do nothing
                    .SelectedIndex = 0
                ElseIf .Items.FindByValue(Session("new_year").ToString) Is Nothing Then
                    '--do nothing
                    .SelectedIndex = 0
                Else
                    '## 1/25/2008   Modified by yang
                    '.Items.FindByValue(Session("new_year").ToString).Selected = True
                    Common.ShowDropDownValue(Me.ddlYear, Session("new_year").ToString, True)
                End If
            End With

            Me.txtContact.Text = Session("new_contact").ToString
            Me.txtPhoneArea.Text = Session("new_phonearea").ToString
            'Me.txtPhoneFront.Text = Session("new_phonefront").ToString
            Me.txtPhonetail.Text = Session("new_phonetail").ToString
            Me.txtCellPhoneArea.Text = Session("new_cellphone").ToString
            Me.txtFaxArea.Text = Session("new_faxarea").ToString
            Me.txtHomePage.Text = Session("new_homepage").ToString
            Me.txtPager.Text = Session("new_pager").ToString
            Me.txtPhone2.Text = Session("new_phone2").ToString
            Me.txtEmail.Text = Session("new_email").ToString

            Me.txtStNo.Text = Session("new_stno").ToString
            Me.txtStName.Text = Session("new_stname").ToString
            'Me.txtAuxAddress.Text = Session("new_x_st").ToString
            Me.txtCity.Text = Session("new_city").ToString
            Me.txtState.Text = Session("new_state").ToString
            Me.txtZip.Text = Session("new_zip").ToString
            Me.txtSubzip.Text = Session("new_subzip").ToString
            'Me.txtCounty.Text = Session("new_county").ToString

            '--Clear All Info
            ' Call Me.Clear_All_Info()

        End If

    End Sub
    ''-----------------------------------------------------------
    ''--Sub:Save_All_Info
    ''--Description:Save All info for page load
    ''--Input:
    ''--Output:
    ''-- 10/05/06 - Created (Daniel)
    ''-----------------------------------------------------------
    'Public Sub Save_All_Info()
    '    '============================================================================================
    '    '==Save All Info=============================================================================
    '    Session("new_fname") = Me.txtFname.Text.Trim()
    '    Session("new_lname") = Me.txtLname.Text.Trim()
    '    Session("new_company") = Me.txtCompany.Text.Trim()
    '    Session("new_acctid") = Me.txtAcctId.Text.Trim()
    '    Session("new_username") = Me.txtUsername.Text.Trim()
    '    Session("new_password") = Me.txtPassword.Text.Trim()
    '    Session("new_cardno") = Me.txtCardNo.Text.Trim()
    '    Session("new_cardtype") = Me.ddlCardType.SelectedValue.Trim()
    '    Session("new_month") = Me.ddlMonth.SelectedValue.Trim()
    '    Session("new_year") = Me.ddlYear.SelectedValue.Trim()

    '    Session("new_contact") = Me.txtContact.Text.Trim()
    '    Session("new_phonearea") = Me.txtPhoneArea.Text.Trim()
    '    'Session("new_phonefront") = Me.txtPhoneFront.Text.Trim()
    '    Session("new_phonetail") = Me.txtPhonetail.Text.Trim()
    '    Session("new_cellphone") = Me.txtCellPhoneArea.Text.Trim()
    '    Session("new_faxarea") = Me.txtFaxArea.Text.Trim()
    '    Session("new_homepage") = Me.txtHomePage.Text.Trim()
    '    Session("new_pager") = Me.txtPager.Text.Trim()
    '    Session("new_phone2") = Me.txtPhone2.Text.Trim()
    '    Session("new_email") = Me.txtEmail.Text.Trim()

    '    Session("new_stno") = Me.txtStNo.Text.Trim()
    '    Session("new_stname") = Me.txtStName.Text.Trim()
    '    'Session("new_x_st") = Me.txtAuxAddress.Text.Trim()
    '    Session("new_city") = Me.txtCity.Text.Trim()
    '    Session("new_state") = Me.txtState.Text.Trim()
    '    Session("new_zip") = Me.txtZip.Text.Trim()
    '    Session("new_subzip") = Me.txtSubzip.Text.Trim()
    '    'Session("new_county") = Me.txtCounty.Text.Trim()
    '    '============================================================================================
    'End Sub

    ''-----------------------------------------------------------
    ''--Sub:Clear_All_Info
    ''--Description:Clear All info for Save
    ''--Input:
    ''--Output:
    ''-- 10/05/06 - Created (Daniel)
    ''-----------------------------------------------------------
    'Public Sub Clear_All_Info()
    '    '===========================================================================
    '    '==Clear All Session========================================================
    '    Session("new_fname") = Nothing
    '    Session("new_lname") = Nothing
    '    Session("new_company") = Nothing
    '    Session("new_acctid") = Nothing
    '    Session("new_username") = Nothing
    '    Session("new_password") = Nothing
    '    Session("new_cardno") = Nothing
    '    Session("new_cardtype") = Nothing
    '    Session("new_month") = Nothing
    '    Session("new_year") = Nothing
    '    Session("new_contact") = Nothing
    '    Session("new_phonearea") = Nothing
    '    'Session("new_phonefront") = Nothing
    '    Session("new_phonetail") = Nothing
    '    Session("new_cellphone") = Nothing
    '    Session("new_faxarea") = Nothing
    '    Session("new_homepage") = Nothing
    '    Session("new_pager") = Nothing
    '    Session("new_phone2") = Nothing
    '    Session("new_email") = Nothing
    '    Session("new_stno") = Nothing
    '    Session("new_stname") = Nothing
    '    Session("new_x_st") = Nothing
    '    Session("new_city") = Nothing
    '    Session("new_state") = Nothing
    '    Session("new_zip") = Nothing
    '    Session("new_subzip") = Nothing
    '    Session("new_county") = Nothing
    '    '===========================================================================
    'End Sub

    Private Sub SetTextBoxValue(ByVal Page As Control, ByVal TextBoxValue As String)
        For Each ctl As Control In Page.Controls
            If TypeOf ctl Is TextBox Then
                CType(ctl, TextBox).Text = TextBoxValue
            Else
                If ctl.Controls.Count > 0 Then
                    SetTextBoxValue(ctl, TextBoxValue)
                End If
            End If
        Next
    End Sub

    Private Sub getAccountInfo()
        Dim objRide As New Rides
        Dim ds As New DataSet
        Try
            ds = objRide.getAllAccountInfo()
            If Not ds Is Nothing Then
                If ds.Tables.Count > 0 Then
                    If ds.Tables(0).Rows.Count > 0 Then
                        Dim i, count As Integer
                        count = ds.Tables(0).Rows.Count
                        Me.hidAcctName.Value = ""
                        Me.hidAcctId.Value = ""
                        For i = 0 To count - 1
                            Me.hidAcctName.Value = Me.hidAcctName.Value & dateSafe(ds.Tables(0).Rows(i)(0)) & "|"
                            Me.hidAcctId.Value = Me.hidAcctId.Value & dateSafe(ds.Tables(0).Rows(i)(1)) & "|"
                        Next

                    End If
                End If
            End If
        Catch ex As Exception
        Finally
            objRide.Dispose()
            objRide = Nothing
        End Try


    End Sub
    Private Function dateSafe(ByVal value As Object) As String
        If value Is Nothing Then
            Return ""
        Else
            Return Convert.ToString(value).Trim
        End If

    End Function

#End Region

#Region "Private JavaScript"

    Private Sub Load_JavaScript()

        'Me.ImageSubmit.Attributes.Add("onClick", "return batchValidate();")
        '## 1/24/2008   Add Verify Credit Card  (Joey)
        Pricing.RegisterValidateCCScript(Me, Me.ImageSubmit, Me.trButton, Me.SubmitHide, 2)
        'Dim VerifyAmount As Double = Val(System.Web.Configuration.WebConfigurationManager.AppSettings("CCVerifyAmount"))
        ''If VerifyAmount >= 0 Then    '## AndAlso Not MySession.OperatorOrder Is Nothing AndAlso MySession.OperatorOrder.card_no.Trim.Length > 0 Then
        'Me.ImageSubmit.Attributes.Add("onclick", "javascript:batchValidate(this);return false;")
        'Me.ClientScript.RegisterStartupScript(GetType(String), "CCVerify", "<script type='text/javascript'>function VerifyCreditCardGoingForward(){document.getElementById('" & Me.SubmitHide.ClientID & "').click();}</script>")
        ''End If
        'Me.ClientScript.RegisterStartupScript(GetType(String), "ShowSubmitButton", "<script type='text/javascript'>function ShowSubmitButton(show){document.getElementById('" & Me.ImageSubmit.ClientID & "').style.visibility=show?'':'hidden';}</script>")


        'Me.ckUserName.Attributes.Add("onClick", "FillText()")

        Me.txtCardNo.Attributes.Add("onfocus", "check_max_length();")
        ' Me.bodyForm.Attributes.Add("onload", "set_defaultinfo_pageload();")
        Me.ddlCardType.Attributes.Add("onchange", "set_defaultinfo_cctypechange()")
        Me.txtCardNo.Attributes.Add("onblur", "set_defaultinfo_ccinfochange()")
        Me.ddlMonth.Attributes.Add("onchange", "set_defaultinfo_ccinfochange()")
        Me.ddlYear.Attributes.Add("onchange", "set_defaultinfo_ccinfochange()")
        '--add by daniel for remove '20070921
        Me.txtFname.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtLname.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtCompany.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtAcctId.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtUsername.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtPassword.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtConfir.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtCardNo.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtContact.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtPhoneArea.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtPhonetail.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtCellPhoneArea.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtFaxArea.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtHomePage.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtPager.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtHomePage.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtPhone2.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtEmail.Attributes.Add("onkeypress", "javascript:entervalues();")

        '--add by daniel 
        Me.txtStNo.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtStName.Attributes.Add("onkeypress", "javascript:entervalues();")
        'Me.txtAuxAddress.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtCity.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtState.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtZip.Attributes.Add("onkeypress", "javascript:entervalues();")
        Me.txtSubzip.Attributes.Add("onkeypress", "javascript:entervalues();")
        'Me.txtCounty.Attributes.Add("onkeypress", "javascript:entervalues();")

    End Sub

#End Region

End Class
